services:

  db:
    image: mongo
    restart: always
    container_name: mongo-olt
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AsuntosPresidenciales
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  cache:
    image: redis:7.4.0-alpine3.20
    container_name: redis-olt
    restart: always
    ports:
      - 6379:6379
    command: "redis-server --loglevel warning --requirepass AsuntosPresidenciales" 
    volumes:
      - ./data:/data/redis.conf
