services:
  db:
    image: postgres:alpine3.20
    container_name: postgres-olt
    restart: always
    shm_size: 256mb # set shared memory limit when using docker-compose
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - chatbot-network

  cache:
    image: redis:alpine3.20
    container_name: redis-olt
    restart: always
    ports:
      - 6379:6379
    command: "redis-server --loglevel warning --requirepass AsuntosPresidenciales"
    volumes:
      - ./data:/data/redis.conf
      
networks:
  chatbot-network:
    name: chatbot-network