services:
  db:
    image: postgres
    container_name: postgres-olt
    restart: always
    shm_size: 128mb # set shared memory limit when using docker-compose
    environment:
      POSTGRES_PASSWORD: example

  cache:
    image: redis:7.4.0-alpine3.20
    container_name: redis-olt
    restart: always
    ports:
      - 6379:6379
    command: "redis-server --loglevel warning --requirepass AsuntosPresidenciales"
    volumes:
      - ./data:/data/redis.conf
